test:
  queue_host:  'localhost'
  elastic_host:  '10.1.3.16'
  metadata_server: 'localhost'
  active_directory: '162.249.218.162'

development:
  queue_host:  'localhost'
  elastic_host:  '10.1.3.16'
  metadata_server:  'timms.turbointernational.com'
  active_directory: '162.249.218.162'

staging:
   queue_host:  '10.0.3.1'
   elastic_host:  'localhost'
   metadata_server: 'timms.turbointernational.com'
   active_directory: '162.249.218.162'

production:
   queue_host:  'localhost'
   elastic_host:  '10.1.3.16'
   metadata_server: 'localhost'
   active_directory: '162.249.218.162'

