test:
  queue_host:  'localhost'
  elastic_host:  '10.1.3.16'
  tcas_host:  'localhost:10000'
  metadata_server: 'localhost'

development:
  queue_host:  'localhost'
  elastic_host:  '10.1.3.16'
  tcas_host:  'localhost:10000'
  metadata_server:  'localhost'

staging:
   queue_host:  '10.0.3.1'
   elastic_host:  'localhost'
   tcas_host:  '10.0.3.1'
   metadata_server: 'timms.turbointernational.com'

production:
   queue_host:  'localhost'
   elastic_host:  '10.1.3.16'
   tcas_host:  'localhost:10000'
   metadata_server: 'localhost'

