test:
  hosts:
    - '10.1.3.15'
    - '10.1.3.16'
    - '10.1.3.17'
  keyspace: turbo_test

development:
  hosts:
    - '10.1.3.15'
    - '10.1.3.16'
    - '10.1.3.17'
  keyspace: turbo_development

staging:
   hosts:
     - '10.8.0.6'
     - '10.8.0.9'
     - '10.8.0.10'
   keyspace: turbo_staging

production:
   hosts:
     - '10.8.0.6'
     - '10.8.0.9'
     - '10.8.0.10'
   keyspace: turbo_production
