test:
  hosts:
    - '10.1.3.15'
    - '10.1.3.16'
    - '10.1.3.17'
  keyspace: turbo_test

development:
  hosts:
    - '10.1.3.15'
    - '10.1.3.16'
    - '10.1.3.17'
  keyspace: turbo_development

staging:
   hosts:
     - '10.0.3.41'
     - '10.0.3.97'
     - '10.0.3.171'
   keyspace: turbo_staging

production:
   hosts:
     - '10.0.3.41'
     - '10.0.3.97'
     - '10.0.3.171'
   keyspace: turbo